<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Chat</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cc083ef3-1559-48a4-a6e4-8cfe8348edfe</testSuiteGuid>
   <testCaseLink>
      <guid>fe4f2d17-bc62-475a-8c63-822d56f7cabf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Chat</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>da169166-eb57-4e6d-9274-3cbc9911bfe2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Chat</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>da169166-eb57-4e6d-9274-3cbc9911bfe2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>text1</value>
         <variableId>1a9f9d73-53b6-4927-ba69-bd1ff51556ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>da169166-eb57-4e6d-9274-3cbc9911bfe2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>text02</value>
         <variableId>230de19c-d4b9-405f-a774-1532c0d7a544</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
