<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Run all test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>37c66927-c667-4cf7-9926-74675aea777d</testSuiteGuid>
   <testCaseLink>
      <guid>c2ca9013-c550-47e4-8bd2-b466f4fd4a0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_TESTCASE/Register_Account_Exist_(huycong2798gmail.com)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8cae64d7-7030-4039-a0a2-8bac2af90407</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_TESTCASE/Login_OK</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bf103361-ed36-4b36-8892-daad4dea8ed5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_TESTCASE/Ping_OK</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>57d18180-5149-41b5-874f-606c71cbcf6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_TESTCASE/ResetPassword_OK</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c6cdbb1a-197d-4bea-906d-3f7bf164650f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_TESTCASE/Check_Exist_Name_Team_(test1)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b28cf831-8a9d-4be6-bce3-f953358bc066</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Create user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3269810-a908-4670-9eb9-2820b8b71421</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fbdeb32-1b99-4ff0-a2b8-02ff8c8d6f6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5570120f-a2d0-4633-8921-17f8801f8bc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b36d43-893b-4409-8887-3af14c67383b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a17cd692-85ea-4dea-a456-3ed9c3f5eaad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Add Team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0c590b5-4393-43c9-898a-974d594fb10f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38b95eb3-eda1-4ec0-a067-18c35ab81742</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c29080c-a3a2-41fe-a6c9-684c12d25ba9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/For loop/Sticker</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f4f5c9fd-84d8-4bd8-bbc2-8efeda05a5f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c00d46ea-1a14-4d25-9b99-80446ca15bef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8462036-765b-419d-9841-5af01daa4b14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71781c1d-61d7-4086-9e3b-06002377dbdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Add Member</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aefab101-1260-45da-abe3-ca1ceb005e8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ceef2c41-4e15-42a5-af98-ee00fc7173fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Forgot Password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eedf2ee-678d-43f6-8321-a3e6c73fe373</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b4bb9d5-9b96-4c5a-892e-f175124250df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Rename Channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c9c616-72cd-4b8f-9856-8e8d72bbd29c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0aaf4d3-8fbd-425e-b642-9c85e77ce297</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/New Channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48d0a2d-c9af-48fb-b0fb-0f8acb98145c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483b1979-e21d-44e3-a66c-f70c1d16a678</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61c2c5d-577f-41a2-bdc7-559be8eb3496</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2babe7e-8179-436c-a9c8-8dba1ea0d4f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b22f8d-0b79-4e69-b6f9-ee584e043d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca1cd4f4-87cb-4602-8d1d-2a6c3da35cc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>385a6330-134d-4425-8103-ab1ab543a060</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6be1f982-d6c4-4d53-9450-a3fcb6b7eba1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Nickname</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcf0d6c9-3121-4a34-92fe-b7cc2c78dae9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c71007c-d471-4c82-9225-eca16623fcfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Team Description</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c49a780-0233-45c8-8542-cb7878a0ddbe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae22c23f-eaa9-4d8e-8647-f35694e0a7d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bae6cf65-88b9-457b-ae14-c14806f814d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bdc312e-ef6a-4a83-958d-2a6b3f2067fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20b2fb98-7463-43c0-a01f-d4e7b4dac5ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b030b50-f7e6-4d1f-a00d-ef086d12b1cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Incoming Webhooks</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>398a7d4c-28a9-4349-8980-02ebf60c4757</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f843054-fc3a-47ea-8f92-bd3a16d8ea55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>759f7e4f-5343-4982-b5b5-948ca9795bc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Update Username</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4e5826d-25d9-4744-adb9-40b5decc2ace</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>237d2ee5-230a-4246-915a-c1d50edce9d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Channel Purpose</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fddfb3a-1466-4861-87f5-bcf0e835afc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f173a6d0-e0a2-4d2f-bb4f-11bb8401631a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/For loop/Chat Message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>90dadd34-6360-4b8e-844e-4e85324011d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/For loop/Change Name</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f0a5e0a9-6435-46c9-bdfc-7b1e1130da93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Team Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>647a3e13-f00f-49e2-a7df-7bbed185b7ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46cd59b4-86f1-4e5f-a6fb-78e874c6a8c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/For loop/Add Member Message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d5be6411-6217-4390-a2a2-29171212c97a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/For loop/Search</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a8d022b5-af5f-4416-9189-b81ad01c6684</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/If_Else_TestCase/Navigate_reset_password_when_input_valid_account</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>62fe3bef-73fe-48fe-9903-47d7c16855d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/If_Else_TestCase/Register_Exist_Account</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c516ec00-650b-4f11-aa9c-152195867732</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/If_Else_TestCase/Shortage_username_input_login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f7101fe9-0550-4ed3-8d2a-aa4724ff84e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/If_Else_TestCase/Input_invalid_email_reset_password</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a9bd52aa-c4d4-4a4e-b7e4-b1145804cbf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/If_Else_TestCase/Shortage_password_input_login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cfb18652-d649-48ad-a91f-d0d22320201d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Channel Header</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2b577ea-5f75-46dc-a258-8e700798ca32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>364cd7cf-6efa-4c30-b2f1-e204617577f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Fullname</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>087274dd-afa2-4c87-805a-570b7c620e4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ad70782-3054-4599-bf5d-b7c7d7f3481d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7f5bb1a-5ddb-4f99-8ecd-4d4fda1abbd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Edit Position</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd40e77-195d-4567-a905-0c644fbc45aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6588daab-f5aa-4a1c-b949-36f24defbde1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Allow User John Team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2878062-6fda-499c-9352-cbdc2274860c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc64d46a-4f13-473c-9555-16948648c0de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Chat</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9f9d73-53b6-4927-ba69-bd1ff51556ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>230de19c-d4b9-405f-a774-1532c0d7a544</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6ae937b-6483-4e8b-8e81-67d4c4cc88c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CallOther/ViewInfoChannel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>26e835c3-9f33-4dd6-a0ba-5a89ab462a73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CallOther/ViewMembersChannel</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
