<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>728bf5d4-de4c-4127-a1c5-fd43665732b3</testSuiteGuid>
   <testCaseLink>
      <guid>210830e5-f9fa-4dee-901e-150a5a8878d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/data-driven/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>94485ce5-5175-4cf6-94bf-3b07c377df40</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data-driven/loginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>94485ce5-5175-4cf6-94bf-3b07c377df40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c00d46ea-1a14-4d25-9b99-80446ca15bef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>94485ce5-5175-4cf6-94bf-3b07c377df40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f8462036-765b-419d-9841-5af01daa4b14</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
